services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: thangitcbg
      POSTGRES_PASSWORD: thangitcbg
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
volumes:
  db-data:
  