ALTER TABLE comments ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE comments ALTER COLUMN user_id TYPE BIGINT;
DROP SEQUENCE IF EXISTS comments_user_id_seq;

ALTER TABLE comments ALTER COLUMN post_id DROP DEFAULT;
ALTER TABLE comments ALTER COLUMN post_id TYPE BIGINT;
DROP SEQUENCE IF EXISTS comments_post_id_seq;
